openapi: 3.1.0

info:
  title: Load Simulation API
  description: An API for simulating various performance scenarios including CPU load, memory usage, and I/O operations.
  version: 1.0.0

servers:
  - url: http://localhost:3000

paths:
  /ping:
    get:
      summary: Check if server is running
      responses:
        '200':
          description: Server is running
          content:
            text/plain:
              schema:
                type: string
                example: "pong\n"

  /time/delay:
    get:
      summary: Delayed response
      parameters:
        - name: ms
          in: query
          schema:
            type: integer
            description: Delay in milliseconds
      responses:
        '200':
          description: Delayed response
          content:
            text/plain:
              schema:
                type: string
                example: "Response delayed by 1000 ms\n"

  /cpu/compute:
    get:
      summary: Compute Fibonacci number
      parameters:
        - name: n
          in: query
          schema:
            type: integer
            description: The nth Fibonacci number to compute
      responses:
        '200':
          description: Computed Fibonacci number
          content:
            text/plain:
              schema:
                type: string
                example: "Fibonacci(40) = 102334155\n"

  /cpu/load:
    get:
      summary: Simulate random CPU usage
      parameters:
        - name: duration
          in: query
          schema:
            type: integer
            description: Duration of the simulation in milliseconds
            default: 10000
        - name: maxLoad
          in: query
          schema:
            type: integer
            description: Maximum CPU load percentage
            default: 100
      responses:
        '200':
          description: CPU load simulation results
          content:
            text/plain:
              schema:
                type: string
                example: "Random CPU load simulated for 10000 ms. Average load: 50.25%\n"

  /memory:
    get:
      summary: Get current memory usage
      responses:
        '200':
          description: Current memory usage
          content:
            application/json:
              schema:
                type: object
                properties:
                  rss:
                    type: string
                  heapTotal:
                    type: string
                  heapUsed:
                    type: string
                  external:
                    type: string
                  arrayBuffers:
                    type: string

  /memory/leak:
    get:
      summary: Create a memory leak
      parameters:
        - name: size
          in: query
          schema:
            type: string
            description: Size of each memory leak (e.g., "1MB")
            default: "1MB"
        - name: count
          in: query
          schema:
            type: integer
            description: Number of memory leaks to create
            default: 1
      responses:
        '200':
          description: Memory leak created
          content:
            text/plain:
              schema:
                type: string
                example: "Created 1 memory leak(s) of size 1048576 bytes each\n"

  /memory/allocate:
    get:
      summary: Allocate memory
      parameters:
        - name: size
          in: query
          schema:
            type: string
            description: Size of memory to allocate (e.g., "1MB")
            default: "1MB"
      responses:
        '200':
          description: Memory allocated
          content:
            text/plain:
              schema:
                type: string
                example: "Allocated 1048576 bytes of memory\n"

  /io/read:
    get:
      summary: Simulate file read operation
      parameters:
        - name: size
          in: query
          schema:
            type: string
            description: Size of file to read (e.g., "1MB")
            default: "1MB"
      responses:
        '200':
          description: File read operation results
          content:
            text/plain:
              schema:
                type: string
                example: "Read 1048576 bytes in 5 ms\n"

  /io/write:
    get:
      summary: Simulate file write operation
      parameters:
        - name: size
          in: query
          schema:
            type: string
            description: Size of file to write (e.g., "1MB")
            default: "1MB"
      responses:
        '200':
          description: File write operation results
          content:
            text/plain:
              schema:
                type: string
                example: "Wrote 1048576 bytes in 10 ms\n"

  /io/network:
    get:
      summary: Simulate network request
      parameters:
        - name: url
          in: query
          schema:
            type: string
            description: URL to fetch
            default: "https://test.k6.io"
      responses:
        '200':
          description: Network request results
          content:
            text/plain:
              schema:
                type: string
                example: "Fetched https://test.k6.io in 200 ms\n"

  /problems/slow-image:
    get:
      summary: Generate a slow-loading image
      parameters:
        - name: complexity
          in: query
          schema:
            type: integer
            description: Complexity of the image generation (affects processing time)
            default: 1
        - name: name
          in: query
          schema:
            type: string
            description: Name used for generating the image
            default: "default"
      responses:
        '200':
          description: Generated image
          content:
            image/jpeg:
              schema:
                type: string
                format: binary
          headers:
            X-Processing-Time:
              schema:
                type: number
              description: Processing time in milliseconds
            X-Timestamp:
              schema:
                type: string
              description: Timestamp of the request

  /problems/slow-image-gallery:
    get:
      summary: Display a gallery of slow-loading images
      responses:
        '200':
          description: HTML page with slow-loading image gallery
          content:
            text/html:
              schema:
                type: string

  /problems/limited-connections/pool/{ms}:
    get:
      summary: Simulate limited connections with a connection pool
      parameters:
        - name: ms
          in: path
          required: true
          schema:
            type: integer
            description: Delay in milliseconds
      responses:
        '200':
          description: Delayed response from connection pool
          content:
            text/plain:
              schema:
                type: string
                example: "Response delayed by 1000 ms\n"
