FROM nginx:mainline@sha256:7272239bd21472f311aa3e86a85fdca0f1ad648995f983ab6e5e7dea665cd233 AS builder

# Install necessary build tools
RUN apt-get update && apt-get install -y wget build-essential libpcre3-dev zlib1g-dev libssl-dev

# Download and extract Nginx source
RUN wget http://nginx.org/download/nginx-$NGINX_VERSION.tar.gz && \
    tar zxf nginx-$NGINX_VERSION.tar.gz

# Download and extract NGINX VTS module
RUN wget https://github.com/vozlt/nginx-module-vts/archive/v0.2.2.tar.gz && \
    tar zxf v0.2.2.tar.gz

# Compile Nginx with VTS module
RUN cd nginx-$NGINX_VERSION && \
    ./configure --with-compat --add-dynamic-module=../nginx-module-vts-0.2.2 && \
    make modules

FROM nginx:mainline@sha256:7272239bd21472f311aa3e86a85fdca0f1ad648995f983ab6e5e7dea665cd233

# Copy the compiled module
COPY --from=builder /nginx-$NGINX_VERSION/objs/ngx_http_vhost_traffic_status_module.so /usr/lib/nginx/modules/

# Enable the module in nginx.conf
RUN echo "load_module modules/ngx_http_vhost_traffic_status_module.so;" > /etc/nginx/modules/vts.conf
