global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'mire'
    static_configs:
      - targets: ['mire:4000']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  - job_name: 'nginx-vts'
    metrics_path: /status/format/prometheus
    static_configs:
      - targets: ['nginx:80']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
